### 0. Library
```{r echo=FALSE}
pkg = c("dplyr")
new.pkg = pkg[!(pkg %in% installed.packages()[,"Package"])]
if (length(new.pkg)) {install.packages(new.pkg,dependencies = TRUE)}
sapply(pkg,require,character.only = TRUE)
```

### 1. Load Data
```{r echo=FALSE}
features_tr <- read.csv('../../data/train/Final_Features.csv', header = TRUE)
# DATA IMPORT FROM RF needed
load('../../../rf_sample.RData')
# rf <- load('../../data/rf_data.RData')
#hund <- sort(fit.0$importance, decreasing = T)[1:100]
#rftophund <- rownames(fit.0$importance)[which(fit.0$importance %in% hund)]
```

### 2. Function to prepare data matrix for kmeans
```{r}
prep_dm = function(data.frame, predictor_names) {
  # Converting data.frame to data.matrix filtered by predictor names given
  df = data.frame
  top_hundred_filtered_df <- df[,which(colnames(df)) %in% predictor_names]
  dm <- data.matrix(top_hundred_filtered_df)
  
  # Normalize dm
  for(z in 1:nrow(dm)){
	  row <- dm[z,]
	  dm[z,] <- row / sqrt(row %*% row)
  }
  
  # Remove NAs if there exist
  if (sum(apply(dm, c(1,2), is.na)) > 0) {
    dm <- na.omit(dm)
  }
  return(dm)
}
```

### 3. Prepare data for K-means
```{r}
# Prepped data
dm_full <- prep_dm(features_tr)
y.tr <- features_tr[,1]

# k-fold CV data (for quick-running one segment)
set.seed(1234)
k = 5 # Number of Folds
num_clusters <- 5 # Number of response variable classes
cv_matrix = matrix(NA, nrow = n, ncol = 5, dimnames = list(seq(1, n)))
nobs <- nrow(dm_full)
ind.cv <- split(sample(1:nobs, replace = FALSE), f = rep(1:5, each = nobs/5))

#data *REMOVE FOR SUBMISSION*
cv1.train <- dm_full[-ind.cv[[1]],]
cv2.train <- dm_full[-ind.cv[[2]],]
cv3.train <- dm_full[-ind.cv[[3]],]
cv4.train <- dm_full[-ind.cv[[4]],]
cv5.train <- dm_full[-ind.cv[[5]],]

#response_var *REMOVE FOR SUBMISSION*
y1.train <- y.tr[-ind.cv[[1]]]
y2.train <- y.tr[-ind.cv[[2]]]
y3.train <- y.tr[-ind.cv[[3]]]
y4.train <- y.tr[-ind.cv[[4]]]
y5.train <- y.tr[-ind.cv[[5]]]
```

### 4. Run k-fold CV
```{r}
l = 8 # Number of multiple of nstart from 20 to 100 (by 10).
for (i in 1:k) {
  dm_cv <- dm_full[-ind.cv[[i]],]
  y_cv <- y.tr[-ind.cv[[i]]]
  for (j in 1:l) {
    kc <- kmeans(dm_cv, centers = num_clusters, nstart = (10+l*10))
  }
}
```


### 5. Run K-means with the best hyperparameter on full data
```{r echo=FALSE}
k_cluster <- kmeans(dm_full, centers = num_clusters, nstart = (1+2))
dt_all <- table(k_cluster$cluster, y.tr)


# To minimize: accuracy & withinss(total within-cluster sum of squares)
km_pred <- k_cluster$cluster
sum(y == km_pred) / length(y)

##
save(fit.0, file = "../../../rf_sample.RData")
```

